import { ConfigService } from '@nestjs/config';
import { randomUUID } from 'node:crypto';
import { PrismaPg } from '@prisma/adapter-pg';
import type { PrismaClient as PrismaClientType } from '../../generated/prisma/client';
import type { PrismaService } from '../prisma/prisma.service';
import { NotificationTriggerInput } from '@metro/shared/notification-contracts';
import type { NotificationTargetsService } from './notification-targets.service';
import type { NotificationSettingsService } from './notification-settings.service';

const testDatabaseUrl = process.env.NOTIFICATIONS_TEST_DATABASE_URL;
const describeIntegration = testDatabaseUrl ? describe : describe.skip;

describeIntegration('notification persistence integration', () => {
  let prisma: PrismaClientType;
  let settings: NotificationSettingsService;
  let fixturesReady = false;
  const userId = `notification-integration-${randomUUID()}`;
  const otherUserId = `notification-integration-other-${randomUUID()}`;
  const targetId = randomUUID();
  const targetIdentityKey = `notification-integration-${randomUUID()}`;
  const endpoint = 'https://fcm.googleapis.com/fcm/send/integration-test';
  const deviceId = randomUUID();
  const validP256dh = Buffer.alloc(65, 1).toString('base64url');
  const validAuth = Buffer.alloc(16, 2).toString('base64url');
  const triggerInput: NotificationTriggerInput = {
    name: 'Integração Linha 1',
    enabled: true,
    days: [1, 2, 3, 4, 5],
    windows: [{ start: '08:00', end: '09:00' }],
    timezone: 'America/Sao_Paulo',
    smart: true,
    leadMinutes: 10,
    intervalMinutes: 15,
    kind: 'rail_status',
    targetIds: [targetId],
    statusMode: 'abnormal',
  };

  beforeAll(async () => {
    // This suite intentionally never reads DATABASE_URL. The dedicated URL
    // must point at an already migrated test database supplied by the caller.
    if (!testDatabaseUrl) return;
    const { PrismaClient } = await import('../../generated/prisma/client');
    const { NotificationSettingsService: SettingsService } = await import(
      './notification-settings.service'
    );
    const adapter = new PrismaPg({ connectionString: testDatabaseUrl });
    prisma = new PrismaClient({ adapter });
    settings = new SettingsService(
      prisma as unknown as PrismaService,
      new ConfigService({
        VAPID_PUBLIC_KEY: validP256dh,
        VAPID_PRIVATE_KEY: Buffer.alloc(32, 3).toString('base64url'),
        VAPID_SUBJECT: 'mailto:notifications@example.com',
      }),
      {} as NotificationTargetsService,
    );

    await prisma.$connect();
    await prisma.notificationTarget.create({
      data: {
        id: targetId,
        identityKey: targetIdentityKey,
        kind: 'rail_line',
        label: 'Linha 1-Azul',
        descriptor: { lineCode: 'L1' },
        available: true,
      },
    });
    await prisma.pushSubscription.create({
      data: {
        id: deviceId,
        user_id: userId,
        endpoint,
        p256dh: validP256dh,
        auth: validAuth,
        label: 'Integração',
      },
    });
    fixturesReady = true;
  });

  afterAll(async () => {
    if (!prisma) return;
    if (!fixturesReady) {
      await prisma.$disconnect();
      return;
    }
    // Every predicate is scoped to a random fixture generated by this suite.
    await prisma.notificationIssueReceipt.deleteMany({ where: { userId } });
    await prisma.notificationTrigger.deleteMany({ where: { userId } });
    await prisma.pushSubscription.deleteMany({ where: { id: deviceId } });
    await prisma.user.deleteMany({ where: { id: userId } });
    await prisma.user.deleteMany({ where: { id: otherUserId } });
    await prisma.notificationTarget.deleteMany({ where: { id: targetId } });
    await prisma.$disconnect();
  });

  it('scopes triggers to the account and enforces optimistic revisions', async () => {
    const created = await settings.saveTrigger(userId, triggerInput);
    expect(created.revision).toBe(0);
    expect(created.targets).toEqual([
      {
        id: targetId,
        kind: 'rail_line',
        label: 'Linha 1-Azul',
        available: true,
      },
    ]);

    await expect(
      settings.saveTrigger(otherUserId, triggerInput, created.id, 0),
    ).rejects.toMatchObject({ status: 404 });

    const updated = await settings.saveTrigger(
      userId,
      { ...triggerInput, name: 'Integração atualizada' },
      created.id,
      created.revision,
    );
    expect(updated.revision).toBe(1);
    await expect(
      settings.saveTrigger(userId, triggerInput, created.id, created.revision),
    ).rejects.toMatchObject({ status: 409 });
  });

  it('reads the configured cloud push state while redacting device metadata', async () => {
    const configuration = await settings.getConfiguration(userId);
    expect(configuration.available).toBe(true);
    expect(configuration.publicKey).toBe(validP256dh);
    expect(configuration.devices).toEqual([
      {
        id: deviceId,
        label: 'Integração',
        createdAt: expect.any(String),
      },
    ]);
    expect(JSON.stringify(configuration)).not.toContain(endpoint);
    expect(JSON.stringify(configuration)).not.toContain(validAuth);
  });

  it('accepts only one receipt for a concurrent same-user issue', async () => {
    const issueKey = `integration-issue-${randomUUID()}`;
    const attempts = await Promise.allSettled(
      [0, 1].map(() =>
        prisma.$transaction((tx) =>
          tx.notificationIssueReceipt.create({
            data: { userId, issueKey },
          }),
        ),
      ),
    );
    expect(
      attempts.filter((attempt) => attempt.status === 'fulfilled'),
    ).toHaveLength(1);
    expect(
      await prisma.notificationIssueReceipt.count({
        where: { userId, issueKey },
      }),
    ).toBe(1);
  });

  it('keeps a receipt after its trigger is deleted', async () => {
    const created = await settings.saveTrigger(userId, triggerInput);
    const issueKey = `integration-delete-issue-${randomUUID()}`;
    await prisma.notificationIssueReceipt.create({
      data: { userId, issueKey },
    });

    await expect(
      settings.deleteTrigger(userId, created.id, created.revision),
    ).resolves.toBe(true);
    await expect(
      prisma.notificationIssueReceipt.findUnique({
        where: { userId_issueKey: { userId, issueKey } },
      }),
    ).resolves.toMatchObject({ userId, issueKey });
  });
});
