import { TransitCity } from './city';

export const SAO_PAULO_CITY = {
  id: 'sp',
  name: 'São Paulo',
  timeZone: 'America/Sao_Paulo',
  locale: 'pt-BR',
  siteTitle: 'Transporte Metropolitano de São Paulo',
  description: 'Informações em tempo real sobre o transporte metropolitano de São Paulo',
  map: {
    center: { latitude: -23.5503953, longitude: -46.6339471 },
    zoom: 11,
  },
  searchPriorityCities: [
  'sao paulo',
  'guarulhos',
  'aruja',
  'santa isabel',
  'itaquaquecetuba',
  'poa',
  'ferraz de vasconcelos',
  'suzano',
  'mogi das cruzes',
  'biritiba mirim',
  'salesopolis',
  'sao cateano do sul',
  'sao caetano do sul',
  'santo andre',
  'manua',
  'maua',
  'ribeirao pires',
  'rio grande da serra',
  'sao bernardo do campo',
  'diadema',
  'taboao da serra',
  'embu das artes',
  'itapecerica da serra',
  'embu-guacu',
  'sao lourenco da serra',
  'juquitiba',
  'cotia',
  'vargem grande paulista',
  'osasco',
  'carapicuiba',
  'barueri',
  'jandira',
  'itapevi',
  'santana de parnaiba',
  'pirapora do bom jesus',
  'cajamar',
  'caieiras',
  'franco da rocha',
  'francisco morato',
  'mairipora',
  'jundiai',
],
} as const satisfies TransitCity;
