.angular
.git
.github
.nx/cache
.nx/workspace-data
.vscode
coverage
dist
node_modules
tmp

.DS_Store
*.log
*.local

dataset-handling
docker
private

apps/*
!apps/metro-frontend-lite
!apps/metro-frontend-lite/**

**/.angular
**/.DS_Store
**/.env*
**/.nx
**/dist
**/node_modules
