.angular
.git
.github
.nx/cache
.nx/workspace-data
.vscode
coverage
dist
node_modules
tmp

.DS_Store
*.log
*.local

docker
private
dataset-handling/target

apps/*
!apps/metro-backend
!apps/metro-backend/**

**/.angular
**/.DS_Store
**/.env*
**/.nx
**/dist
**/node_modules
apps/metro-backend/generated
